title = "DevSecOps Gitleaks Config"

[extend]
useDefault = true

[[rules]]
id = "sacramento-api-token"
description = "Detecta tokens internos de Sacramento Software"
regex = '''SACRAMENTO-[A-Za-z0-9]{32}'''
tags = ["token", "internal", "sacramento"]

[allowlist]
description = "Ejemplos permitidos en documentación"
paths = [
  '''docs/.*'''
]